#!/bin/bash

EXPORT_MODE=true
NEXT_PUBLIC_MATOMO_URL=https://analytics.aurorafast.co.uk
NEXT_PUBLIC_MATOMO_SITE_ID=9
NEXT_PUBLIC_CRISP=62b1921c-e285-41ea-9c01-dcdb98c550be
NEXT_PUBLIC_LANGUAGE=en
NEXT_PUBLIC_BACKEND_SERVER=https://br.aurorafast.co.uk/
NEXT_PUBLIC_TAG_MANAGER=
NEXT_PUBLIC_ANALYTICS
NEXT_PUBLIC_BACKEND_SERVER1=https://channels.voltaindustrie.com/
NEXT_PUBLIC_IS_TRIAL=yes

# Delete the old .env file if it exists
rm -f .env

# Create a new .env file with the specific values
echo "NEXT_PUBLIC_MATOMO_URL=$NEXT_PUBLIC_MATOMO_URL" > .env
echo "NEXT_PUBLIC_MATOMO_SITE_ID=$NEXT_PUBLIC_MATOMO_SITE_ID" >> .env
echo "NEXT_PUBLIC_CRISP=$NEXT_PUBLIC_CRISP" >> .env
echo "NEXT_PUBLIC_LANGUAGE=$NEXT_PUBLIC_LANGUAGE" >> .env
echo "NEXT_PUBLIC_BACKEND_SERVER=$NEXT_PUBLIC_BACKEND_SERVER" >> .env
echo "NEXT_PUBLIC_TAG_MANAGER=$NEXT_PUBLIC_TAG_MANAGER" >> .env
echo "NEXT_PUBLIC_ANALYTICS=$NEXT_PUBLIC_ANALYTICS" >> .env
echo "NEXT_PUBLIC_BACKEND_SERVER1=$NEXT_PUBLIC_BACKEND_SERVER1" >> .env
echo "NEXT_PUBLIC_IS_TRIAL=$NEXT_PUBLIC_IS_TRIAL" >> .env


yarn dev